name: "Deploy Docker Image"

concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
    # run every day at midnight
    schedule:
        - cron: '0 0 * * *'
    push:
        branches:
            - '*'
            - '!dependabot/**'
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

env:
    # Use docker.io for Docker Hub if empty
    #REGISTRY: ghcr.io
    REGISTRY: ''
    # use DOCKERHUB_USERNAME as the name maybe different from the GitHub username
    IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/rdfind
    TAG: latest

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            -
                name: Checkout repository
                uses: actions/checkout@v4

            -
                name: Get branch name
                id: branch-name
                uses: tj-actions/branch-names@v8

            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v3
                with:
                    platforms: all
            # Workaround: https://github.com/docker/build-push-action/issues/461
            -
                name: Setup Docker buildx
                uses: docker/setup-buildx-action@v3
            -
                name: Available platforms
                run: echo ${{ steps.buildx.outputs.platforms }}

            # Login against all registries

            -
                name: Login to DockerHub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            # Extract metadata (tags, labels) for Docker
            # https://github.com/docker/metadata-action
            -
                name: Extract Docker metadata
                id: meta
                uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            -
                name: Set Version number
                run: |
                    VER=1.0
                    TAG=test
            -
                name: Set build datetime
                run: |
                    TIMESTAMP=$(date -u +'%Y-%m-%d T%H:%M:%SZ')
                    echo "BUILD_DATE=$TIMESTAMP" >> $GITHUB_ENV
            
            # Build and push Docker image with Buildx
            # https://github.com/docker/build-push-action
            -
                name: Build and push Docker image
                id: build-and-push
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: ${{ github.event_name != 'pull_request' }}
                    platforms: linux/amd64
                    tags: |
                      ${{ env.IMAGE_NAME }}:${{ env.TAG }}
                      ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
                    labels: ${{ steps.meta.outputs.labels }}
